= Create a new project

== Mandatory steps

=== Perquisites

=== Testerra setup

The Testerra mobile framework is deployed to https://bintray.com/bintray/jcenter.

For Testerra mobile you need at least the following dependencies for Gradle or Maven.

.build.gradle
[source,gradle,role="primary"]
----
apply plugin: 'java'

// Its highly recommended to normalize your project to Unicode
compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = "UTF-8"

dependencies {
    compile 'eu.tsystems.mms.tic.testerra:mobile:1-SNAPSHOT'
}
----

.pom.xml
[source,xml,role="secondary"]
----
<project>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <!-- Its highly recommended to normalize your project to Unicode -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.tsystems.mms.tic.testerra</groupId>
            <artifactId>mobile</artifactId>
            <version>1-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
----

If you're already a user of the Testerra framework or you are familiar with it, you will now know about the following project structure.
In some text paragraphs we will just link the Testerra framework documentation, because the setup is mostly the same as for mobile.

=== Create project structure

Your project structure should comply with these simple constraints.

* `src/main` Contains all the code for your project like <<PageObjects>>, Models and language specific resources.
* `src/test` Contains all test related code like your Tests, Test-Suites, Test-Data and Testerra related setup.

=== Create test.properties

Create a new file at `src/test/resources` with the name `test.properties`.

.test.properties
[source,properties,subs="attributes"]
----
#Set the browser
{browser}=mobile_chrome
tt.browser.version=

#Set the start page
{baseurl}=http://example.org

#Set your experitest mobile cloud configuration
tt.mobile.server.host=localhost
tt.mobile.server.port=8889

tt.mobile.grid.user=your_user_name
tt.mobile.grid.password=your_password
tt.mobile.grid.project=your_project

#set your device filter
tt.mobile.device.filter=os.type=android
----

TIP: All defined properties can be overwritten later by adding system parameters to your command +
 (e.a `-D{browser}=mobile_safari`)

All supported mobile browsers are listed HERE [PLEASE ADD LINK TODO]

=== Create Page Class

Now its time to create a first simple page class.
It should be saved at path `src\main\java\<package>`.
The following example represents the website example.org.
It contains one possible link to click and one method to test.

.New page class
[source,java]
----
import eu.tsystems.mms.tic.testframework.pageobjects.Page;

public class ExamplePage extends Page {

    @Check
    private GuiElement moreInformationLink = new GuiElement(driver, By.partialLinkText("More information"));

    public ExamplePage(WebDriver driver) {
        super(driver);
    }

    public void clickOnMoreInformation() {
        moreInformationLink.click();
    }
}
----

[TIP]
======
The basic Page class added all the page object functionality of Testerra to your project.
See <<PageObjects>> chapter for more details.

The GuiElement describes the elements like links, buttons, etc. on your page.
Learn more about GuiElements in <<GuiElements>>.
======

=== Create Test Class and Test Method

Next create a simple test class with a test method.
The test class needs to extend from `TesterraTest`.
It should be located at path `src\test\java\<package>`.
To stick to the example above, here is a very simple test class which navigates to example.org and clicks on the link defined on the example page.
Again, probably imports must be made in IDE.

.New test class
[source,java]
----
public class ExampleTest extends TesterraTest {

  @BeforeSuite(alwaysRun = true)
    public void setupMobileDriver() {

        MobileDriver driver = MobileDriverManager.getMobileDriver();

        if (driver.getActiveDevice() == null) {
            driver.reserveDeviceByFilter();
        }
    }


    @AfterSuite(alwaysRun = true)
    public void teardownMobileDriver() {
        MobileDriverManager.releaseDriverFromThread();
    }

    @Test
    public void testT01_My_first_test() {

        WebDriver driver = WebDriverManager.getWebDriver();

        // Call the base url, because "getMobileDriver" will just give you a session of the mobile
        driver.get(PropertyManager.getProperty("tt.baseurl"));

        ExamplePage examplePage = PageFactory.create(ExamplePage.class, driver);
        examplePage.clickOnMoreInformation();
    }
}
----

NOTE: By extending from `TesterraTest` all runtime features are loaded automatically.

=== Setup a test suite

To customize the executing of your tests, you have to create a TestNG suite file `suite.xml` and locate it at `src/test/resources`

.suite.xml
[source,xml]
----
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite1" verbose="1" thread-count="10" configfailurepolicy="continue" parallel="false">
    <test name="Test1" parallel="methods">
        <classes>
            <class name="ExampleTest"/>
        </classes>
    </test>
</suite>
----

=== Setup test build target

In order to get tests to work, you need to setup a build target `test` in your project.

.build.gradle
[source,gradle,role="primary"]
----
test {
    useTestNG() {
        suites file('src/test/resources/suite.xml')
    }

    testLogging {
        outputs.upToDateWhen { false }
        showStandardStreams = true
    }

    // Important: Forward all JVM properties like proxy settings to TestNG
    options {
        systemProperties(System.getProperties())
    }

    // basically execution returns "GREEN" (framework exits with exit code > 0 if there were failures)
    ignoreFailures = true
}
----

.pom.xml
[source,xml,role="secondary"]
----
<project>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>mySuite</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skip>false</skip>
                            <suiteXmlFiles>
                                <suiteXmlFile>src/test/resources/suite.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----

=== Run the tests

Finally you are good to run your very first test by entering the following command:

.Gradle
[source,bash,role="primary"]
----
gradle test
----

.Maven
[source,bash,role="secondary"]
----
mvn test -PmySuite
----

=== Testerra Report

The Testerra test report is automatically generated and can be found at `<project>/testerra-report/index.html`.

