= Create a new project

include::properties/property-attributes.adoc[]

== System requirements

* Testerra Mobile is based on Java.
You need a JDK 8 or later.
* Execute your tests with *Maven* or *Gradle*
* You need a connection to your mobile device farm (Self Hosted at your LAN or use an internet instance)
** You will need a valid access key to connect to your cloud instance

== Mandatory steps

=== Testerra mobile setup

The Testerra mobile framework is deployed to https://bintray.com/bintray/jcenter.

For Testerra mobile you need at least the following dependencies for Gradle or Maven.

.build.gradle
[source,gradle,role="primary"]
----
apply plugin: 'java'

dependencies {
    compile 'eu.tsystems.mms.tic.testerra:appium:1-SNAPSHOT'
}
----

.pom.xml
[source,xml,role="secondary"]
----
<project>
    <dependencies>
        <dependency>
            <groupId>eu.tsystems.mms.tic.testerra</groupId>
            <artifactId>appium</artifactId>
            <version>1-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
----

If you aren't already a user of the Testerra framework, please refer to the Testerra framework documentation to setup your initial project structure.

=== Customize test.properties

According to the Testerra framework documentation you have to setup a `test.properties` file.
Now you have to append it with some mobile related test properties.

.test.properties
[source,properties,subs="attributes"]
----
#Set the browser
{browser}=mobile_chrome

#Set the start page
{baseurl}=http://example.org

#Set your mobile cloud configuration
{mobile_server_url}=https://mobiledevicecloud.example.com/wd/hub
{mobile_access_key}=https://mobiledevicecloud.example.com/wd/hub

#set your device filter - will filter for android devices only
{mobile_device_query_ios}=@os='ios' and @category='PHONE'
{mobile_device_query_android}=@os='android' and @category='PHONE' and @version='10'
----

TIP: All defined properties can be overwritten later by adding system parameters to your command +
(e.a `-D{browser}=mobile_safari`)

=== Create Test Class and Test Method

To create an initial test class and test method please take a look at the Testerra framework documentation.
The setup is equal to it, with the following difference.

.Mobile test class
[source,java]
----
public class ExampleTest extends TesterraTest {

    @Test
    public void testT01_My_first_test() {

        final WebDriver driver = WebDriverManager.getWebDriver();
        final AppiumDriver<MobileElement> appiumDriver = appiumDriverManager.fromWebDriver(driver);

        appiumDriver.rotate(ScreenOrientation.LANDSCAPE);
        driver.get(PropertyManager.get("tt.baseurl"));
    }
}
----

=== Setup a test suite and execute

This part is equal to the Testerra framework, so please follow the instructions as documented in Testerra framework documentation.
